apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: public-http
  namespace: gateway-system
  labels:
    app.kubernetes.io/name: public-http
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: terra
    terra/environment: dev
spec:
  gatewayClassName: nginx
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway-access: public