apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-api-content
  namespace: apps
  labels:
    app.kubernetes.io/name: backend-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: terra
    terra/environment: dev
data:
  index.html: |
    backend-api is running
