---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-api-config
  namespace: apps
spec:
  encryptedData:
    BACKEND_API_TOKEN: AgAx5NQIm6xIT+n/pm9fGAnM8AWXzpx4mpB8ylPelaWwMR30FGpY4daOAIN7IP6LQWg38Ca1sLFPBTsjcrbIqa0MF+gdoSP+z0fmh630pEp99JaidL6ylLTcztUR0IH58vtYC+SVGsTXLmItlnulxgWSfNCXeu2iAlDv0VHXkQKJRVB6rZ4ZphIeOMo4xwJ8mA1XoVpLwxc6OQ4V4nI67hIL6SdmoIEgmw62Lx0qkQMo3cTERb3UiKDvAuUSPEA6KNgAS8NPalleHvOUh/iy66FIq567ccGwmHmNHaL/6jn7dx2mz21hP0zZ5IMAf9qVJeUYvaZGpVPU6EoRuvxzZn1vgCCGbx5FkYa7EeGwr4EpK03YHPu/HxOPFFt6Yss+AG8HsrLIoBvYwN/JPvkrzUlNdPzYvvuvLhCJo/WNwq54/gZ9DfG9MRVWpVSS0wV+q/xai3WXLT4vS/o5uyxpDmRX+R46fEwBaw3Amoo+Hr/i21INKs07r6qyWymjoZAnET3d0q/18kly8bLMbhSRgTm3Z3+/SJ9xRhymuubjl+8zJv3laCZJNyrLr1rKnr6hFo6nKscM1eX4Hdv0mJSMwjcpdDdVmnGMN9Av/lnabZ3TJb++yQf9BXx/Go2kP4merTJl6l/aLfeZIxDcMUrRk0KDYG3+z6pKYEmrmy54SLYDo1w7NpSAA3XaOqPHH0HugLEmnsn/7uQs+FyUCXZ5DAtjKbcV0tuNdJ/j1vA=
  template:
    metadata:
      name: backend-api-config
      namespace: apps
