apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-api
  namespace: apps
  labels:
    app.kubernetes.io/name: backend-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: terra
    terra/environment: dev
automountServiceAccountToken: false
