apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terra-dev-sealed-secrets
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: terra
    terra/environment: dev
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: terra-dev-platform
  source:
    repoURL: https://github.com/bitnami-labs/sealed-secrets.git
    targetRevision: helm-v2.17.3
    path: helm/sealed-secrets
    helm:
      releaseName: sealed-secrets
      values: | 
        fullnameOverride: sealed-secrets-controller
        namespace: sealed-secrets
        serviceAccount:
          create: true
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            memory: 256Mi
        podSecurityContext:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        containerSecurityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false